language: objective-c
    
os: osx
osx_image: xcode9.1

script: 
  - xcodebuild
  - xcodebuild test -scheme ABCDAutoResizingTextView -configuration Debug -destination "platform=iOS Simulator,name=iPhone SE"
